export const FLAT_LIST_REF = 'FLAT_LIST_REF_';
export const LAST_SCROLL_OFFSET = 'LAST_SCROLL_OFFSET_';
export const SCROLL_DIRECTION = 'SCROLL_DIRECTION_';
export const IS_DRAGGING = 'IS_DRAGGING_';
export const IS_MOMENTUM_SCROLLING = 'IS_MOMENTUM_SCROLLING_';
export const IS_DIRTY = 'IS_DIRTY_';
